base_lr: 0.0005
batch_size: 256
best_cnet: null
best_rnet: null
bps_size: 4096
c_weights_path: null
cuda_id: 0
dataset_dir: null
expr_ID: V00
kl_coef: 0.005
latentD: 16
log_every_epoch: 2
n_epochs: 500
n_neurons: 512
n_workers: 10
reg_coef: 0.0005
rhm_path: null
seed: 4815
try_num: 0
use_multigpu: false
vpe_path: null
work_dir: null
load_on_ram: False